CREATE TABLE Stocks(
StockId uuid,
CompanyName VARCHAR(250),
NseListedName VARCHAR(250),
BseListedName VARCHAR(250),
ClosingSharePrice FLOAT,
CurrentTradingPrice FLOAT,
TodaysHigh FLOAT,
TodaysLow FLOAT,
High52W FLOAT,
Low52W FLOAT,
FaceValue FLOAT,
NumberOfShares FLOAT,
MarketCaptilization FLOAT,
CashInM FLOAT,
DebtInM FLOAT,
EnterpriceValue FLOAT,
DividentYield FLOAT,
Strength VARCHAR(250),
Weakness VARCHAR(250),
Opportunities VARCHAR(250),
Threats VARCHAR(250),
Ownership INT,
Valuation FLOAT,
Efficiency INT,
Financials INT,
NoOfTimesViewed INT
)